### PR TITLE
Upgrade to python 3.6 and install requests lib

### PR DESCRIPTION
**Pull request by charlesverdad**
- Upgrade to python3.6 Because python3.5 doesn't have types and f-strings.
- Install requests library for https://github.com/Canva/canva/pull/92571

### CODE REVIEW

**Comment by charlesverdad** [comment]
>We can safely upgrade python I think, but the requests library shouldn't be installed globally. A requirements.txt in the using package should be the preference there.

Hey @joscha I considered that but wouldn't that mean pip installing it on every build?

**Comment by joscha** [comment]
Correct. We can cache it if needed but making every dependency we have part of the base image is not going to scale.

**Comment by joscha** [comment]
The alternative is to build a separate image - base it on a python base image and add the dependencies you need on top of it. That might be a good idea anyway so we don't pile dependencies for a single use case onto this image.

**Comment by charlesverdad** [comment]
Sounds good. I'll close this and create my own image 😄

**Pull request closed without merging**
